# -*- coding: utf-8 -*-
"""Store chunks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaIlB_qGg54gfWTcvgy1nn79gvAiJops
"""

import requests
import re
import os

# Updated URL pointing to the "Subjects" list (Algorithms, System Architecture, etc.)
# If you want language-specific books, use: .../main/books/free-programming-books-langs.md
MARKDOWN_URL = "https://raw.githubusercontent.com/EbookFoundation/free-programming-books/main/books/free-programming-books-subjects.md"

SAVE_DIR = "./downloaded_pdfs"

def download_pdfs_from_github_markdown(markdown_url, save_directory):
    if not os.path.exists(save_directory):
        os.makedirs(save_directory)

    print("Fetching markdown file...")
    response = requests.get(markdown_url)

    if response.status_code != 200:
        print(f"Failed to fetch markdown. Status code: {response.status_code}")
        return

    markdown_text = response.text

    # 1. Extract ALL links from the markdown file
    all_links = re.findall(r'\[.*?\]\((https?://[^\)]+)\)', markdown_text)

    # 2. Filter only the links that contain '.pdf' (handles query parameters)
    pdf_links = [link for link in all_links if '.pdf' in link.lower()]

    # Remove duplicates
    pdf_links = list(set(pdf_links))

    print(f"Found {len(pdf_links)} PDF links. Starting download...")

    # 3. Download each PDF (Limiting to first 10 for testing)
    for link in pdf_links:
        try:
            # Clean up the filename so it saves properly
            filename = link.split('/')[-1].split('?')[0]
            if not filename.endswith('.pdf'):
                filename += '.pdf'

            filepath = os.path.join(save_directory, filename)

            print(f"Downloading: {filename}")

            # Using a custom User-Agent to prevent academic servers from blocking the script
            headers = {'User-Agent': 'Mozilla/5.0'}
            pdf_response = requests.get(link, stream=True, timeout=15, headers=headers)

            if pdf_response.status_code == 200:
                with open(filepath, 'wb') as f:
                    for chunk in pdf_response.iter_content(chunk_size=1024):
                        f.write(chunk)
            else:
                print(f"  -> Server returned status {pdf_response.status_code}")

        except Exception as e:
            print(f"  -> Failed to download {link}: {e}")

# Run the extraction
download_pdfs_from_github_markdown(MARKDOWN_URL, SAVE_DIR)



import requests
import re
import os

# The specific GitHub markdown files for Logic/Math and Algorithms/Theory
MARKDOWN_URLS = [
    "https://raw.githubusercontent.com/EbookFoundation/free-programming-books/main/books/free-programming-books-math.md",
    "https://raw.githubusercontent.com/EbookFoundation/free-programming-books/main/books/free-programming-books-subjects.md"
]

SAVE_DIR = "./downloaded_pdfs/conceptual"

# Keywords mapped directly from your SkillQuest roadmap
TARGET_KEYWORDS = [
    "logic", "discrete", "pattern", "problem solving", "algorithm",
    "data structure", "computational", "abstraction", "pseudocode",
    "architecture", "system", "theory"
]

def download_targeted_pdfs(markdown_urls, save_directory, keywords):
    if not os.path.exists(save_directory):
        os.makedirs(save_directory)

    headers = {'User-Agent': 'Mozilla/5.0'}
    total_downloaded = 0

    for url in markdown_urls:
        print(f"\nFetching list from: {url.split('/')[-1]}")
        response = requests.get(url)

        if response.status_code != 200:
            print("Failed to fetch markdown.")
            continue

        # Regex to capture BOTH the Book Title (Group 1) and the URL (Group 2)
        # Format: [Book Title](https://link.com/book.pdf)
        matches = re.findall(r'\[(.*?)\]\((https?://[^\)]+)\)', response.text)

        for title, link in matches:
            # Check if it's a PDF AND if the title matches our roadmap keywords
            title_lower = title.lower()
            if '.pdf' in link.lower() and any(keyword in title_lower for keyword in keywords):

                # Clean up filename
                filename = link.split('/')[-1].split('?')[0]
                if not filename.endswith('.pdf'):
                    filename += '.pdf'

                filepath = os.path.join(save_directory, filename)

                # Skip if we already downloaded it
                if os.path.exists(filepath):
                    continue

                print(f"Match found: '{title}'")
                print(f" -> Downloading: {filename}")

                try:
                    pdf_response = requests.get(link, stream=True, timeout=15, headers=headers)
                    if pdf_response.status_code == 200:
                        with open(filepath, 'wb') as f:
                            for chunk in pdf_response.iter_content(chunk_size=1024):
                                f.write(chunk)
                        total_downloaded += 1
                    else:
                        print(f"    x Server rejected: {pdf_response.status_code}")
                except Exception as e:
                    print(f"    x Download failed: {e}")

    print(f"\nTargeted scraping complete. Downloaded {total_downloaded} new conceptual PDFs.")

# Run the targeted extraction
download_targeted_pdfs(MARKDOWN_URLS, SAVE_DIR, TARGET_KEYWORDS)

import os
import sys
import subprocess
import uuid
import time
import urllib3

# ---------------------------------------------------------
# Programmatic Package Installer (Perfect for Google Colab)
# ---------------------------------------------------------
required_packages = {
    "azure.cosmos": "azure-cosmos",
    "pypdf": "pypdf",
    "langchain_text_splitters": "langchain-text-splitters",
    "dotenv": "python-dotenv",
    "google.generativeai": "google-generativeai"
}

for module, package in required_packages.items():
    try:
        __import__(module)
    except ImportError:
        print(f"[{package}] is not installed. Installing it now programmatically...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Import installed libraries safely
from azure.cosmos import CosmosClient, PartitionKey
from pypdf import PdfReader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from dotenv import load_dotenv
import google.generativeai as genai

# Disable warning messages for local SSL bypass
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Load environment configurations if .env exists
load_dotenv()

# Detect Google Colab environment
IN_COLAB = False
try:
    import google.colab
    IN_COLAB = True
except ImportError:
    pass

# Setup Credentials with Multi-Environment Support (Colab Secrets, Environment Variables, dotEnv)
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
COSMOS_URL = os.environ.get("COSMOS_ENDPOINT")
COSMOS_KEY = os.environ.get("COSMOS_KEY")

if IN_COLAB:
    print("\n" + "="*60)
    print("Google Colab Environment Detected!")
    print("Attempting to load credentials from Colab Secrets...")
    print("="*60 + "\n")
    
    try:
        from google.colab import userdata
        if not GEMINI_API_KEY:
            GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
    except Exception:
        pass
        
    try:
        if not COSMOS_URL:
            COSMOS_URL = userdata.get("COSMOS_ENDPOINT")
    except Exception:
        pass
        
    try:
        if not COSMOS_KEY:
            COSMOS_KEY = userdata.get("COSMOS_KEY")
    except Exception:
        pass

    # Prompt user interactively if secrets are missing in Colab
    if not GEMINI_API_KEY or GEMINI_API_KEY == "your_gemini_api_key_here":
        import getpass
        print("\n[REQUIRED] Gemini API Key is missing.")
        GEMINI_API_KEY = getpass.getpass("Please enter your Google AI Studio GEMINI_API_KEY: ")
        
    if not COSMOS_URL or COSMOS_URL == "https://cosmos-db:8081":
        print("\n[REQUIRED] Cosmos DB URL is missing or set to internal docker hostname.")
        print("Note: If you are using a cloud Cosmos DB, enter its URI (https://xxx.documents.azure.com:443/).")
        print("If you are tunneling your local emulator, enter the public tunnel URL (e.g. https://xxx.ngrok-free.app).")
        COSMOS_URL = input("Please enter your COSMOS_ENDPOINT: ")
        
    if not COSMOS_KEY or COSMOS_KEY == "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==":
        import getpass
        print("\n[REQUIRED] Cosmos DB Key is missing or using default emulator key.")
        print("Note: If using cloud Cosmos DB, enter your primary key.")
        print("If using the local emulator via tunnel, hit Enter to use the default emulator key.")
        user_input_key = getpass.getpass("Please enter your COSMOS_KEY (leave empty to use default key): ")
        if user_input_key:
            COSMOS_KEY = user_input_key

# Set defaults if not resolved (mainly for local development)
if not COSMOS_URL:
    COSMOS_URL = "https://localhost:8081"
if not COSMOS_KEY:
    COSMOS_KEY = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="

# Setup Gemini API Key
if not GEMINI_API_KEY or GEMINI_API_KEY == "your_gemini_api_key_here":
    print("[WARNING] GEMINI_API_KEY is not set. Embedding generation might fail.")
genai.configure(api_key=GEMINI_API_KEY)

# Handle SSL certificate verification bypass for local emulator/tunnel endpoints
verify = True
url_lower = COSMOS_URL.lower()
if "localhost" in url_lower or "127.0.0.1" in url_lower or "cosmos-db" in url_lower or "ngrok" in url_lower or "cloudflare" in url_lower or "localtunnel" in url_lower:
    verify = False
    print(f"Local or Tunneled database endpoint detected: '{COSMOS_URL}'. Bypassing SSL certificate verification...")

print(f"Connecting to Azure Cosmos DB at: {COSMOS_URL}")
client = CosmosClient(COSMOS_URL, credential=COSMOS_KEY, connection_verify=verify)

print("Connecting to database CourseRAG_DB and verifying resources...")
database = client.create_database_if_not_exists(id="CourseRAG_DB")
container = database.create_container_if_not_exists(
    id="CourseMaterials",
    partition_key=PartitionKey(path="/id"),
    offer_throughput=400
)

# ---------------------------------------------------------
# Fetch list of already uploaded PDFs to skip them
# ---------------------------------------------------------
print("Checking database for previously uploaded files...")
try:
    # Query Cosmos DB for all unique filenames currently stored
    query = "SELECT DISTINCT c.source FROM c"
    existing_items = container.query_items(
        query=query,
        enable_cross_partition_query=True
    )
    # Create a fast-lookup set of filenames already in the DB
    processed_files = {item['source'] for item in existing_items if 'source' in item}
except Exception as e:
    print(f"Could not fetch previously processed files (might be first run): {e}")
    processed_files = set()

print(f"Found {len(processed_files)} previously processed files in the database. These will be skipped.")

# 2. Define Gemini embedding function
def get_gemini_embedding(text):
    """Generate high-quality 768-dimension vector embedding using text-embedding-004 or fallback."""
    for model_name in ["models/text-embedding-004", "models/gemini-embedding-001", "models/embedding-001"]:
        try:
            response = genai.embed_content(
                model=model_name,
                content=text,
                task_type="retrieval_document"
            )
            return response['embedding']
        except Exception as e:
            err_str = str(e).lower()
            if "not found" in err_str or "404" in err_str or "not supported" in err_str:
                # Silently try next fallback model
                continue
            print(f"Embedding error with {model_name}: {e}")
            break
            
    # Return 768-dimension zero array as safety backup so seeder does not fully crash
    return [0.0] * 768

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
)

# 3. Define target directories
PDF_DIRECTORIES = ["./downloaded_pdfs", "./downloaded_pdfs/conceptual"]

# 4. Batch Processing Loop
total_chunks_uploaded = 0

for directory in PDF_DIRECTORIES:
    if not os.path.exists(directory):
        continue
        
    print(f"\nScanning directory: {directory}...")
    for filename in os.listdir(directory):
        if not filename.endswith('.pdf'):
            continue

        # Skip the file if it is already in our processed_files set
        if filename in processed_files:
            print(f"Skipping: {filename} (Already exists in database)")
            continue

        file_path = os.path.join(directory, filename)
        print(f"\nProcessing: {filename}...")

        try:
            reader = PdfReader(file_path)
            file_chunk_count = 0

            for page_num, page in enumerate(reader.pages):
                page_text = page.extract_text()

                if page_text:
                    chunks = text_splitter.split_text(page_text)

                    for chunk in chunks:
                        # Generate the 768-dimensional Gemini embedding
                        vector_embedding = get_gemini_embedding(chunk)

                        document = {
                            "id": str(uuid.uuid4()),
                            "text": chunk,
                            "source": filename,
                            "page": page_num + 1,
                            "embedding": vector_embedding
                        }

                        # Upload to Cosmos DB Emulator container
                        container.upsert_item(document)
                        file_chunk_count += 1
                        total_chunks_uploaded += 1
                        
                        # Add a tiny delay to respect rate limits
                        time.sleep(0.1)

            print(f"  -> Success! Uploaded {file_chunk_count} chunks from {filename}.")

        except Exception as e:
            print(f"  -> Skipping {filename} due to an error: {e}")

print(f"\nBatch processing complete! A total of {total_chunks_uploaded} new chunks were uploaded to Azure Cosmos DB.")